# DO NOT FORGET to define BITBOX environment variable 

NO_USB=1

NAME = letterbox
GAME_C_FILES = main.c nonsimple.c
GAME_H_FILES = nonsimple.h
GAME_C_OPTS += -DVGAMODE_320

# see this file for options
include $(BITBOX)/lib/bitbox.mk

