# DO NOT FORGET to define BITBOX environment variable 

NAME = superbox
GAME_C_FILES = nonsimple.c main.c
GAME_H_FILES = nonsimple.h
GAME_C_OPTS += -DVGAMODE_320

# see this file for options
include $(BITBOX)/lib/bitbox.mk

