# DO NOT FORGET to define BITBOX environment variable 

USE_SDCARD = 1      # allow use of SD card for io

NAME = fulltile
GAME_C_FILES = main.c nonsimple.c
GAME_H_FILES = nonsimple.h
GAME_C_OPTS += -DVGAMODE_640

# see this file for options
include $(BITBOX)/lib/bitbox.mk

