# DO NOT FORGET to define BITBOX environment variable 

NAME = vertex3d
GAME_C_FILES = main.c vview3d.c bb3d.c
GAME_H_FILES = vview3d.h bb3d.h

GAME_C_OPTS += -DVGAMODE_640

# see this file for options
include $(BITBOX)/lib/bitbox.mk

