# DO NOT FORGET to define BITBOX environment variable 

NAME = face640
GAME_C_FILES = bb3d.c world.c main.c
GAME_H_FILES = bb3d.h world.h

GAME_C_OPTS += -DVGA_MODE=640

# see this file for options
include $(BITBOX)/kernel/bitbox.mk

