# DO NOT FORGET to define BITBOX environment variable 

# see lib/simple.h for modes:
VGA_SIMPLE_MODE=5
# do a `make clean` if you change the simple view mode.

NAME = vbuff3d
GAME_C_FILES = main.c bb3d.c
GAME_H_FILES = bb3d.h

# see this file for options
include $(BITBOX)/lib/bitbox.mk

