# DO NOT FORGET to define BITBOX environment variable 

NO_VGA = 1 # comment out to get graphics

NAME = noisebox
GAME_C_FILES = main.c
GAME_H_FILES = 

GAME_C_OPTS += -DVGAMODE_320

# see this file for options
include $(BITBOX)/lib/bitbox.mk
