# DO NOT FORGET to define BITBOX environment variable 

NAME = face3d
GAME_C_FILES = nonsimple.c bb3d.c world.c main.c
GAME_H_FILES = nonsimple.h bb3d.h world.h

# see this file for options
include $(BITBOX)/lib/bitbox.mk

