# DO NOT FORGET to define BITBOX environment variable 

NAME = fface3d
GAME_C_FILES = bb3d.c nonsimple.c main.c
GAME_H_FILES = bb3d.h nonsimple.h

# see this file for options
include $(BITBOX)/lib/bitbox.mk

