# DO NOT FORGET to define BITBOX environment variable 

NAME = wires3d
GAME_C_FILES = main.c wview3d.c bb3d.c
GAME_H_FILES = wview3d.h bb3d.h

GAME_C_OPTS += -DVGAMODE_640 #-DDEBUG

# see this file for options
include $(BITBOX)/lib/bitbox.mk

