# DO NOT FORGET to define BITBOX environment variable 

USE_SDCARD = 1      # allow use of SD card for io

NAME = 16tiles
GAME_C_FILES = edit.c fill.c nonsimple.c tiles.c sprites.c main.c
GAME_H_FILES = edit.h fill.h nonsimple.h tiles.h sprites.h
GAME_C_OPTS += -DVGAMODE_320

# see this file for options
include $(BITBOX)/lib/bitbox.mk

